<!DOCTYPE html>
<html>
<body>

<?php
// Running Throgh the Tasks
echo "My first PHP script!";
?>

<?PHP

// What code studio do you use? Im currently using VS Code but i dont mind changing
$install = "PHP";
echo "Im learning $Install"
?>

<?php

// Comments are allways simple this is a single line one 

/*
This is a Multi Line comment its the same in JS

Saying that being able to leave out parts of code whilst testing is a handy tool
*/

$Num1 = 15

$Num2 = 2

//Example of a comment in code:

$Ans = $Num1 /* +30 */ * $Num2;

echo $Ans;


?>

<?php
ECHO "Hello World!<br>";
echo "Hello World!<br>";
EcHo "Hello World!<br>";

// Bad coding Practice it should all follow the same rules
?>



</body>
</html>